apiVersion: v2
name: quota-operator
description: A Helm chart for the quota-operator
type: application
version: v0.6.0
appVersion: v0.6.0
home: https://github.com/openmcp-project/quota-operator
sources:
  - https://github.com/openmcp-project/quota-operator